# Etapa base: node + build
FROM node:20

# Establece el directorio de trabajo
WORKDIR /app

# Copia archivos necesarios
COPY package*.json tsconfig*.json ./
RUN npm install

# Copia el código fuente
COPY src ./src

# Compila TypeScript
RUN npm run build

# Expone el puerto
EXPOSE 3000

# Comando de inicio
CMD ["node", "dist/index.ts"]
